### ISSUE TITLE
Implement Dynamic Rendering Base [Frontend]

### ISSUE THREAD

**Issue by eyu776** [COSC481W-2024Winter/Fictionary-Frontend#16]
## User story
As someone who enjoys games, I want to play a game that feels complete and has each part working well. I get annoyed when games glitch and I get the wrong page displayed to me for no apparent reason. When this happens it ends up being game breaking and I don't feel like playing the game anymore.

- Persona: A person who enjoys web-based games or drawing games of any age.
- Feature: A responsive website page and structure that allows for proper game flow. Pages are displayed to right roles in the game.
- Business value: This is what holds the entire game together, it is necessary to determine the main structure of the game. With this base page properly structured, player will be able to play a game that has structure and logic to it.

## Tasks 
- [x] Define user roles by a react state.
- [x] Convert current react pages into components on our main game page (Room.js) by converting into modals that can be toggle the display on and off.
- [x] Create "next"/"continue" buttons to trigger the toggling display on or off for components.
- [x] Choose what to render based on the user's permissions

## Acceptance Criteria
The following pages remain static:
- Home page
- Rules page
- Host page 
- Guest/Join 

The following pages are dynamic:
- Begin at lobby 
- Categories voting
- Drawing
- Voting
- Results
- Scoreboard 

- Should be able to go through general logic of the game; flow should be established 
- Should be accomplished on one singular page
- Should have understandable and readable code - this page will be the main aspect of the game and needs to be well documented and organized.

**Comment by eyu776** [comment]
This is a video showing code I worked on to build the functionality of the dynamic rendering for persistent websocket connection, because I wrote a lot of dummy code/components that won't be committed to the branch/repository.

[Screen recording 2024-02-12 10.03.27 PM.webm](https://github.com/COSC481W-2024Winter/Fictionary-Frontend/assets/124838733/5c888eee-cf02-4311-8e39-9dbfa2254a1d)

### **Too long; didn't watch?**
* Video shows forcing JavaScript to refresh the page is required otherwise modals in Room.js doesn't work. Why this is? I don't know and I spent two hours too many looking for a better fix. But it has something to do with the "sources" tab on chrome's developer tools. This causes the page to double refresh when redirecting from home page (Home.js) to the game page (Room.js), but the first "refresh" is the URL redirection via react-router-dom which redirects the page without actually refreshing!!!
* Video shows a test button from the home page (Home.js) that redirects the page to the game page (Room.js) while passing the props for enabling host permissions. The host permissions are also stored in a react state so we can use it to enable other host specific features besides being the first to draw.
* Video shows closing and displaying components that were converted to modals and the websocket connection stays persistent even though the connection is only set up on the first render of the page.
* Video shows the host having permission to draw and the other user (guest) does not have permissions to draw but is still able to see the host's drawing.

**Comment by eyu776** [comment]
Reopening issue for writing tests because the person doing the testing framework PBI wants me to write my own tests.
