### ISSUE TITLE
UI cohesion

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Frontend#17]
## user story
As a person who enjoys games, I like games that have nice design and look good. Games that don't have any color and have really small fonts do not motivate me to play. I can't see buttons if they are small and in corners, I like them to be visible and noticeable. 

## Task
- [x] create tailwind classes for main elements
- [x] Class for buttons, secondary buttons 
- [x] Class for tables
- [x] Classes for different headers
- [x] Defined font

## Acceptance criteria
- All main elements should have a predefined style
- Buttons, tables, font, headers should have default style
- Styling is based mostly on the Figma model (on UI inspo)
