### ISSUE TITLE
Adding images to Rules page

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Frontend#23]
## User Story
I like to play games that have rules properly laid out so I can understand how to play easily. If there are pictures I can really understand step by step whats going on and how to play.

- Persona: Someone who enjoys playing games and likes images.
- Feature: Players can see images that relate to the rules in the rules page.
- Business value: Players will understand better the rules and enjoy it more. The images make the UI attractive.

## Tasks:
- [ ] Take screenshots of game as it goes on
- [ ] Make divs for each specific image
- [ ] Place on corresponding rule in rules.js

## Acceptance Criteria:
- Screenshots are related to the rules they are with
