### ISSUE TITLE
Reformatting UI

### ISSUE THREAD

**Issue by StellarSparks** [COSC481W-2024Winter/Fictionary-Frontend#30]
## User Story
When I play games, I like a user interface that looks appealing and items I have to look at are not too far away from each other. More compact interfaces are more conformable and nice to look at, than a UI that is spread out all over my screen.

## Tasks
- [x] create format for canvasses 
- [x] make UI more compact, elements are too far from each other
- [x] Add any new default styling to index.css if necessary

## Acceptance Criteria
- The UI needs to be reformatted to be more compact 
- the canvases should all be square across pages
- Consistent styling across all pages
