### ISSUE TITLE
Documentation: Keeping the Readme file updated

### ISSUE THREAD

**Issue by CreamTW** [COSC481W-2024Winter/Fictionary-Frontend#34]
## User Story
As the game gets more completed and more complicated as it progresses, I should be able to understand how the game works when looking at the gitHub page instead of going to the page itself. That way, my expectations of the game will be what the readme has as features instead of my assuming what features the game can have later.

- Persona: person who is interested in web based games
- Feature: Readme is maintained to keep users than play the game informed
- Business Value: Players of the game can keep up with changes that re made to it and have a proper understanding on how to play it.

## **TASKS**

- [ ] When a feature is added or when the game rules change, the readme file updates its changes.
- [ ] Have different changes of the readme depending on if it was completed on the frontend or backend.
- [ ] Have the readme files also look pretty and easy to understand to the average user.

## **Acceptance Criteria**

- Have both readme files have up to date information about the game.
- Have the readme files be styled for github so that navigating the file is simple to understand.
- Have the readme files be readable.
