### ISSUE TITLE
Guess Voting/Scoring [Frontend]

### ISSUE THREAD

**Issue by StellarSparks** [COSC481W-2024Winter/Fictionary-Frontend#35]
### User Story:

As someone who plays games with different roles, I like it when players who are better at playing a certain role are acknowledged for it at the end of the game.

**Persona:** Someone who plays games with multiple roles.
**Feature:** Celebrating the performance of players based on their roles.
**Business Value:** Players will feel rewarded by the game and/or motivated to earn the award in future games.

### Tasks:

- [x] Display which points each player has earned at the end of each round.
- [x] Display a table of the players total scores at the end of the game.
- [x] Assign awards at the end of the game to the player with the highest total score, the player with the highest artist score, and the player with the highest trickster score.

### Acceptance Criteria:

- Points should be labeled explicitly as "trickster points" or "artist points" at the end of rounds so that players know that there are different points for each role.
- If the player with the highest score is also the player with the highest trickster score or artist score, award the second place trickster and artist scores with a second place prize on the results page so that they can tell if they still performed well in a role.
