### ISSUE TITLE
Making/Displaying Guesses

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Frontend#36]
## User story
As someone who likes drawing games and guessing games, I enjoy games where I can play competitively and trick people to win. It is more interesting than regular games. I want be to be rewarded for how good I can guess and trick others.

- Persona: A user who enjoys playing games.
- Feature: Let people make "fake guesses" to trick other players.
- Business Value: Makes the game different from most others, adds and interesting mechanic to the game which makes it stand out.

## Tasks

- [x] Receive user guesses from guess input box at the end of the drawing round
- [x] Display all user guesses on buttons on guessing page
- [x] Buttons should be associated with the user that wrote the guess to determine scoring later

## Acceptance Criteria
- Player should be limited to 15 number of characters per guess.
- Guesses should be sent at the end of the drawing section.
