### ISSUE TITLE
Canvas Customization

### ISSUE THREAD

**Issue by barbwynn** [COSC481W-2024Winter/Fictionary-Frontend#37]
# User Story

As someone who enjoys drawing games, I think that the most important aspect of a drawing game is the amount of options given to the artist. I like to have at least a few color options and the ability to change the brush size as well as erase any mistakes I make.

- Persona: A person who enjoys drawing games
- Feature: The ability to customize the artist's drawing options
- Business Value: Players get a more enjoyable artist experience increasing the enjoyability of the game overall.

# Tasks

- [x] Change color based on user input
- [x] Change brush size based on user input
- [x] Remove anything drawn via erasure

# Acceptance Criteria

- The artist can change the brush's color
- The artist can change the brush's size
- The artist can erase whatever they draw
- Non-artists cannot modify these aspects
