### ISSUE TITLE
Canvas functionality

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Frontend#52]
## user story
I love drawing games. When I play drawing games I want a drawing board that feels responsive. It feels very janky to play games where you click to draw and nothing happens and you have to keep trying until you succeed. I like to be able to draw without worrying about bugs or glitches that interrupt my drawing for any reason. Drawing with unresponsive drawing boards also makes it really hard to play because you can't draw properly.

- Persona: Person who enjoys playing drawing games of any age.
- Feature: Working drawing board where user can draw using mouse and holding click (if they are the artist)
- Business Value: Main feature and mechanic of the game, it is essential for the game to be played as intended.

## Task
- [x] Canvas is drawable
- [ ] Backend mimics front end drawing 
- [x] Implement drawing permission based on roles
- [ ] Make drawing visible to other players

## Acceptance criteria
- black color only (not other colors yet)
- Only artist can draw
- Clear board after results
- Others can view the board
