### ISSUE TITLE
add: room ID validation

### ISSUE THREAD

**Issue by jasminebroton** [COSC481W-2024Winter/Fictionary-Frontend#54]
User story: As an avid gamer, I've come to expect a high quality user experience from my games. Therefore I'd like to make sure when I'm joining a room, I either join a room that already exists or don't join at all.

**Tasks**

- [x] Add communication between backend and database to store existing IDs
- [x] Add communication between frontend and database to validate IDs 

**Acceptance Criteria** 

- [x] Created IDs should appear in the database
- [x] 'Join room' should not create a new room
- [x] Join room should provide error message when attempting to join a room that does not currently exist
