### ISSUE TITLE
Add word fetching to drawing page

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Frontend#55]
### User story
As someone who likes drawing games, I like to have multiple themes and options to draw from. I makes the game replayable and more fun because there a more possibilities. I also like to have the word I have to draw being displayed clearly when I have to draw.
- Persona: User who enjoys playing drawing games
- Feature: Users are given a randomized word from a category to draw
- Business Value: having multiple options keeps the player engaged, will ad replayability value to the game.

### Tasks:
- [x] Include fetch request in the drawing page 
- [x] find out whats wrong with CORS / other url errors
- [x] Alter DigitalOcean environment variables (if necessary)
- [x] display word in drawing game (randomized from category)

### Acceptance criteria:
- Word is selected from category sent from category voting
- Word is random
- Only Artist can see the word
