### ISSUE TITLE
add: displaying drawings on multiple pages

### ISSUE THREAD

**Issue by jasminebroton** [COSC481W-2024Winter/Fictionary-Frontend#57]
User story: When I game, I don't want to have to focus too hard. If I'm playing a drawing game, I'd like to be able to see the drawing later to be reminded what it looks like.

**Tasks**

- [ ] Send drawings to the socket connection
- [ ] Fetch and display drawings in the UI from the socket 

**Acceptance Criteria**

- [ ] Upon submission, the drawing produced by the Artist will be sent to the backend
- [ ] Only one submission per artist 
- [ ] Drawings should be shown in the UI where indicated
